name: ForSyDe-SystemC
description: The SystemC implementation of ForSyDe 
theme: jekyll-theme-slate

show_downloads: true

parent-url: https://forsyde.github.io

maintainer:
  name: shaniaki
  url: https://github.com/shaniaki


github-releases:
  zip_url: https://api.github.com/repos/forsyde/ForSyDe-SystemC/zipball/master
  tar_url: https://api.github.com/repos/forsyde/ForSyDe-SystemC/tarball/master

## google analytics
google_analytics: UA-113668562-1

## paths to exclude from the site generation
exclude: [script, Gemfile, Gemfile.lock, jekyll-theme-slate.gemspec]